version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]

  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
